[build]
    command = "npx expo export:web"
    publish = "web-build"
    functions = "functions"

[functions]
    directory = "functions"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[dev]
    command = "expo start --web"